name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "15.4"
    - name: Build
      run: |
        SIMULATOR_ARCH="$(uname -m)"
        swift build -v \
          -Xswiftc "-sdk" \
          -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
          -Xswiftc "-target" \
          -Xswiftc "${SIMULATOR_ARCH}-apple-ios13.0-simulator"
